Wall/urls.py
from django.conf.urls import url, include  # Notice we added include  

urlpatterns = [
    url(r'^', include('apps.wall_app.urls',namespace='wall')),
]

apps/wall_app/urls.py
from django.conf.urls import url
from . import views           # This line is new!

app_name = 'wall'
urlpatterns = [
    url(r'^$', views.index, name='my_home'),
    url(r'^success', views.success, name='my_success'),
    url(r'^newsFeed', views.newsFeed, name='my_newsFeed'),
    url(r'^login', views.login, name='my_login'),
    url(r'^register', views.register, name = 'my_register'),
    url(r'^clear$', views.clear, name = 'my_clear'),
    url(r'^send$', views.send, name = 'my_send'),
    url(r'^comment', views.comment, name = 'my_comment'),
    #url(r'^semi_users/(?P<id>\d+)/update$', views.update, name='my_update'),
    #url(r'^semi_users/(?P<id>\d+)/delete$', views.delete, name='my_delete'),
    #url(r'^semi_users/(?P<id>\d+)', views.display, name='my_show'),
]   

apps/wall_app/models.py
# Inside your app's models.py file
from __future__ import unicode_literals
from django.db import models
# Create your models here.
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


class RegistrationManager(models.Manager):
    def basic_validator(self,postData):
        errors ={}
        #names rules
        if len(postData['first_name']) < 3:
            errors["first_name"] = "Name should be more than 2 characters long!"
        if len(postData['last_name']) < 3:
            errors["last_name"] = "Last Name should be more than 2 characters long!"
        
        #Password rules
        if len(postData['password']) < 8:
            errors["password"] = "Passowrd should be more than 2 characters long!"
        elif not re.search("[A-Z]", postData['password']): 
            errors["password"] = "Password must have at least 1 uppercase letter"
        elif not re.search("[0-9]", postData['password']): 
            errors["password"] = "Password must have at least 1 number"
        elif re.search("\s",  postData['password']):
            errors["password"] = "Password must have no empty spaces"
        elif postData['password'] != postData['confirm_password']:
            errors["password"] = "Passwords don't match"
        #email rules
        if len(postData['email']) < 1:
            errors["email"] = ("Email cannot be blank!")
        elif not EMAIL_REGEX.match(postData['email']):
            errors["email"] = ("Invalid Email Address!")

        return errors



class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    
    # *************************
    # Connect an instance of BlogManager to our Blog model overwriting
    # the old hidden objects key with a new one with extra properties!!!
    objects = RegistrationManager()
    # *************************

class Message(models.Model):
    text = models.TextField(max_length=1000)
    sender = models.ForeignKey(User, related_name="sentMessages", on_delete=models.CASCADE , null = True)
    receiver = models.ForeignKey(User, related_name="myMessages", on_delete=models.CASCADE , null = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    comment = models.TextField(max_length=1000)
    updater_id = models.ForeignKey(User, related_name="comment", on_delete=models.CASCADE)
    message_id = models.ForeignKey(Message, related_name="comment", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/wall_app/views.py
from django.shortcuts import render,HttpResponse, redirect
from django.contrib import messages
from django.urls import reverse
import bcrypt
from .models import User, Message, Comment
from django.db.models import Q
# Create your views here.
#render index Page
def index(request):
    if('id' in request.session):
        return redirect(reverse('wall:my_success'))
    return render(request,"wall/index.html")
#register a new user
def register(request):
    errors = User.objects.basic_validator(request.POST)
    if len(errors):
        # if the errors object contains anything, loop through each key-value pair and make a flash message
        for key, value in errors.items():
            messages.error(request, value, key)
        # redirect the user back to the form to fix the errors
        return redirect('wall:my_home')
    #if not redirected then we create new user with hashed password.
    hash1=  bcrypt.hashpw(request.POST['password'].encode('utf-8'), bcrypt.gensalt())
    newUser = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'],
                                 email = request.POST['email'], password= hash1.decode('utf-8'))
    messages.success(request, "Users succesfully created!")
    print(newUser.first_name)
    request.session['id'] = newUser.id
    return redirect(reverse('wall:my_success'))

#log into user
def login(request):
    if request.method == "POST":
        #checks if there is a user with email.
        loginUser = User.objects.filter(email=request.POST['email'])
        if not loginUser:
            messages.error(request, "Failed to login",'login')
            return redirect(reverse('wall:my_home'))
        #if found compare the hash of the given password to the saved hash.
        print(loginUser.first().password)
        if bcrypt.checkpw(request.POST['password'].encode('utf-8'), loginUser.first().password.encode() ):
            request.session['id'] = loginUser.first().id
            messages.success(request, "Login Succesful!")
            return redirect(reverse('wall:my_success'))
        messages.error(request, "Failed to login",'login')
        return redirect(reverse('wall:my_home'))

def success(request):
    users = User.objects.exclude(id=request.session['id'])

    context ={
        "all_but_me" : users,
        "name" : User.objects.get(id=request.session['id']).first_name,
        "myMessages" : User.objects.get(id=request.session['id']).myMessages.all().order_by('-created_at'),
        "id" : request.session['id']
        }
    return render(request,"wall/myWall.html",context)

def newsFeed(request):
    users = User.objects.filter(~Q(id=request.session['id']))
    #messages = User.objects.get(id=request.session['id']).myMessages.all()
    context ={
        "all_but_me" : users,
        "name" : User.objects.get(id=request.session['id']).first_name,
        "myMessages" : Message.objects.all().order_by('-created_at'),
        "id" : request.session['id']
        }
    return render(request,"wall/newsFeed.html",context)


def comment(request):
    if request.method == "POST":
        Comment.objects.create(comment=request.POST['content'],updater_id=User.objects.get(id=request.session['id']),message_id=Message.objects.get(id=request.POST['msg_id']))
    
    return redirect(reverse('wall:my_home'))

def send(request):
    if request.method == "POST":
        Message.objects.create(text=request.POST['content'],sender=User.objects.get(id=request.session['id']),receiver=User.objects.get(id=request.POST['ToWho']))
    return redirect(reverse('wall:my_home'))
def clear(request):
    request.session.clear()
    return redirect(reverse('wall:my_home'))

apps/wall_app/templates/wall/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <title>Welcome Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <h2>
            Login
        </h2>
        <!-- login form -->
        <form action={%url 'wall:my_login' %} method="post">
            {% csrf_token %}
            {% for message in messages %}
            {% if message.tags == "login error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}
            <div class="form-group">
                <label for="usr">Email:</label>
                <input type="text" class="form-control" id="usr" name="email">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
            <button type="submit" class="btn btn-success">Login</button>
        </form>
        <!-- registration form -->
        <form action={%url 'wall:my_register' %} method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="firstname">First Name:</label>
                <input type="text" class="form-control" id="firstname" name="first_name">
            </div>
            {% for message in messages %}
            {% if message.tags == "first_name error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}

            <div class="form-group">
                <label for="lastname">Last Name:</label>
                <input type="text" class="form-control" id="lastname" name="last_name">
            </div>
            {% for message in messages %}
            {% if message.tags == "last_name error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" id="email" name="email">
            </div>
            {% for message in messages %}
            {% if message.tags == "email error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}

            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
            {% for message in messages %}
            {% if message.tags == "password error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}
            <div class="form-group">
                <label for="confpwd">Confirm Password:</label>
                <input type="password" class="form-control" id="confpwd" name="confirm_password">
            </div>
            {% for message in messages %}
            {% if message.tags == "confirm_password error" %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {%endif%}
            {% endfor %}
            <button type="submit" class="btn btn-success">Register</button>
        </form>
    </div>
</body>
</html>

apps/wall_app/templates/wall/myWall.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Your Wall</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Coding Dojo Wall</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href={%url 'wall:my_newsFeed' %}>News Feed</a></li>
                <li><a href={%url 'wall:my_clear' %}>logout</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <h2>Your Messages</h2>
        <p><strong>Select one to see content</strong></p>
        <div class="panel-group" id="accordion">
            {%for message in myMessages%}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{message.id}}">{{message.sender.first_name}}   {{message.created_at}}</a>
                    </h4>
                </div>
                <div id="{{message.id}}" class="panel-collapse collapse in">
                    <div class="panel-body">
                        {{message.text}}
                    </div>
                    <form class="comment-form" action={%url 'wall:my_comment' %} method="post">
                        {% csrf_token %}
                        <input type="hidden" name="msg_id" value={{message.id}} />
                        <label for="comment">Post a comment:</label>
                        <textarea class="form-control" rows="2" id="comment" name="content"></textarea>
                        <button type="submit" class="btn btn-primary"> Comment </button>
                    </form>
                    {%if message.comment %}
                    {%for comment in message.comment.all %}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <p class="comment-text">{{comment.comment}}</p>
                            <p class="comment-text">{{comment.updater_id.first_name}}</p>
                            <p class="comment-text">{{comment.created_at}}</p>
                        </div>
                    </div>
                    {%endfor%}
                    {%endif%}
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
    <div class="container">
        <div class="form-group">
            <form action={%url 'wall:my_send' %} method="post" id="cmtform">
                {% csrf_token %}
                <label for="message">Send a Message:</label>
                <select class="form-control" id="sel1" name="ToWho">
                    {%for user in all_but_me%}
                    <option value={{user.id}}>{{user.first_name}}</option>
                    {%endfor%}
                </select>
                <input type="hidden" name="id" value="{{id}}" />
                <textarea class="form-control" rows="5" id="message" name="content"></textarea>
                <button type="submit" class="btn btn-primary"> Send </button>
            </form>
            
        </div>
    </div>
</body>
</html>

apps/wall_app/templates/wall/newsFeed.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Your news Feed</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'wall/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Coding Dojo Wall</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li class="active"><a href={%url 'wall:my_newsFeed' %}>News Feed</a></li>
                <li><a href={%url 'wall:my_clear' %}>logout</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <h2>Your Messages</h2>
        <p><strong>Select one to see content</strong></p>
        <div class="panel-group" id="accordion">
            {%for message in myMessages%}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{message.id}}">{{message.sender.first_name}}   {{message.created_at}}</a>
                    </h4>
                </div>
                <div id="{{message.id}}" class="panel-collapse collapse in">
                    <div class="panel-body">
                        {{message.text}}
                    </div>
                    <form class="comment-form" action={%url 'wall:my_comment' %} method="post">
                        {% csrf_token %}
                        <input type="hidden" name="msg_id" value={{message.id}} />
                        <label for="comment" class="commentLabel">Comments:</label>
                        <!-- show comments on message -->
                        {%if message.comment %}
                        {%for comment in message.comment.all %}
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <p class="comment-text">{{comment.comment}}</p>
                                <p class="comment-footer">By {{comment.updater_id.first_name}} {{comment.updater_id.last_name}}</p>
                                <p class="comment-footer"> On {{comment.created_at}}</p>
                            </div>
                        </div>
                        {%endfor%}
                        {%endif%}
                        <div class="panel-group">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" href="#comment_{{message.id}}">Comment</a>
                                    </h4>
                                </div>
                                <div id="comment_{{message.id}}" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <textarea class="form-control" rows="2" id="comment" name="content"></textarea>
                                        <button type="submit" class="btn btn-primary"> Comment </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
    <div class="container">
        <div class="form-group">
            <form action={%url 'wall:my_send' %} method="post" id="cmtform">
                {% csrf_token %}
                <label for="message" class="sendLabel">Send a Message:</label>
                <select class="form-control" id="sel1" name="ToWho">
                    {%for user in all_but_me%}
                    <option value={{user.id}}>{{user.first_name}}</option>
                    {%endfor%}
                </select>
                <input type="hidden" name="id" value="{{id}}" />
                <textarea class="form-control" rows="5" id="message" name="content"></textarea>
                <button type="submit" class="btn btn-primary"> Send </button>
            </form>

        </div>
    </div>
</body>
</html>